[package]
name = "octree"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
glam = "0.27.0"
rand = "0.8.5"
rand_distr = "*"
macroquad = "0.4"

[lib]
crate-type = ["lib"]
test = true
bench = true
doc = true

[[example]]
name = "simple"
